#+TITLE: Frequently Answers and Questions about Damegender
#+h3: David Arroyo Menéndez 
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez 
#+EMAIL: davidam@gnu.org
#+DATE: 17/06/2020
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />

* Ethical Values
** Is Damegender reducing the gender gap? 
We use say Damegender can reduce the gender gap. To reduce the gender
gap is an [[https://www.un.org/sustainabledevelopment/gender-equality/][objective in United Nations]], so the states must help to this
objective. To reduce the gender gap we must measure where it is
happening. Damegender is Free Software with data extracted from the
states, so we can measure about men and women with a critical point of
view that can be reviewed by peers.

** Can I guess the sexual orientation with Damegender? 
Not, you can't. You only guess the gender, such as the states is
registering it. All states is using a binary ideology about the gender
(male and female) and in Damegender too.

** Is Damegender Free Software?

Yes, it's. We are using GPLv3. You can read the license in all files
and the full text in LICENSE file.

** Why are you guessing male or female?
Some aplications are guessing unknown, but in Damegender we are
thinking that this option is ok if the name is not in database. In
this case, we are providing a binary response using machine learning.

Some radical LGTB associations are claiming by non binary options
about gender, that is not an option for us due to there not states
acknowledging this need and providing Open Datasets about names and
gender. The states are providing us the datasets.

** Are you predicting ethical problems using machine learning for guess names?
Machine learning is similar than statistics, so you don't be afraid
using maths when you are coding. Damegender can be used on a laptop,
so that you are not depending of a very big company as Amazon for use
the machine learning. 

If you introduce a word such as chair, table, etc. you could have a
gender ethical problem because you are giving a gender to a thing. In
Afghanistan there are women with no names referenced as things, so the
problem is dangerous. You can use Damegender to understand if the
person is talking about a male or a female, but you must understand
that you must not self reference or reference to another people as
things. Please be careful, it's your responsability.

* Installation
** How can I install it?

#+BEGIN_SRC bash
$ pip3 install damegender[all]
#+END_SRC

** Where is the scripts to execute Damegender?

In my GNU/Linux installation you can access to Damegender from:

#+BEGIN_SRC bash
/usr/local/lib/python3.7/site-packages/damegender
#+END_SRC

You can guess a name with

#+BEGIN_SRC bash
$ python3 main.py Clara
#+END_SRC
* Using it
** Why must I use Damegender?
+ If you want determine gender gap in free software projects or mailing lists.
+ If you don't know the gender about a name
+ If you want research with statistics about why a name is related with males or females.
+ If you want use a free gender detection tool from a name from a command with open data.
+ If you want use the main solutions in gender detection (genderize,
  genderapi, namsor, nameapi and gender guesser) from a command.
** How can I determine gender gap in free software projects or mailing lists.

You can count males and females in a git project with:

#+BEGIN_SRC bash
python3 git2gender.py https://github.com/davidam/orgguide-es.git --directory="/tmp/clonedir"
#+END_SRC

You can count males and females in a mailing list with:

#+BEGIN_SRC bash
python3 mail2gender.py http://mail-archives.apache.org/mod_mbox/httpd-announce/
#+END_SRC

** How can I determine gender about a name?
#+BEGIN_SRC 
$ python3 main.py David
#+END_SRC
** What's the scripts to research with statistics?
+ confusion.py
+ accuracy.py
+ errors.py
+ roc.py
+ pca-components.py and pca-features.py
+ infofeatures.py

** How can I know the most used names?
#+BEGIN_SRC bash
$ python3 top.py es --sex=female
#+END_SRC
** Give me the race about a name in USA!
#+BEGIN_SRC bash
$ python3 ethnicity.py David
#+END_SRC
** What countries are related about a name?
#+BEGIN_SRC bash
$ python3 nameincountries.py David
#+END_SRC
** What countries are related about a surname?
#+BEGIN_SRC bash
$ python3 surnameincountries.py David
#+END_SRC
** How many people are using a surname?
#+BEGIN_SRC bash
$ python3 surname.py Menéndez --total=us
#+END_SRC
** Give me some real examples about count males and females in communities
#+BEGIN_SRC bash
$ python3 count-debian-gender.py
$ python3 count-scientifics.py
#+END_SRC
** How can I use another solutions in gender detection from damegender?
First, you must register an account in genderapi, genderize, namsor or
nameapi:

#+BEGIN_SRC bash
$ python3 apikeyadd.py
#+END_SRC

Later, you can guess the name choosing the rigth api:

#+BEGIN_SRC bash 
$ python3 api2gender.py David --api=genderize
#+END_SRC

