* v0.4.8

Bug fixes related to pretty_gg_list in accuracy.py

* v0.4.7
The method pretty_gg_list has been rewritten allowing some combination
of csv or json files as arguments. This will be very useful for a
Damegender non dependent of Lucia&Helena dataset. So, very good
datasets saved in files/names/names_tests will can be used for check
benchmarks of accuracies, precision, f1score, recall, ...

With identical goal in mind, many methods has been added to
dame_statistics.py respecting the jargon math (true_negative,
false_negative, false_positive, true_positive). Remember that
there are many datasets stored in files/names/names_tests and tests
are welcome!

More countries has been added to orig2.py

* v0.4.6
Added the 58 most popular italian names (29 males and 29 females)
retrieved from istat (the italian statistics office).

In the goal to make very easy replicate the building of the dataset,
we are starting to rewrite all scripts about process orig files
from official statistics from states to damegender csv files.
As soon as possible the only command will be orig2.py simplifying
the processing. Some datasets has been updated in the process.

* v0.4.5
Dumping names and surnames for all countries from Wikidata.
surnames.py and surnamesincountries.py has been updated to give
support to Wikidata.

For each country, we are choosing official statistics, but if there
not official statistics from now we are allowing to the users the
dataset provided by wikidata. The user will receive a messsaga about
it, due to that Wikidata could be giving very few names in some
countries, so the quality is worst with Wikidata.

* v0.4.4

Official Datasets:
+ [X] Argentina: 42800 names, 24587 females, 18456 males, 77583 surnames
+ [X] Great Britain: 459848 names, 34326 males, 51195 females

Great Britain has several statistical offices divided by Great Britain
regions. So we must do more long calculus if you find bugs, please
send to Damegender, for example, with a github issue. Thanks in advance.

Cleaning code:
+ [X] Replaced lxml by xml python native, lxml was doing problems in MacOS
+ [X] Reducing lines of code in top.py

* v0.4.3
New features:
+ get-wikidata-names.py: to download names from wikidata in a specific country
+ get-wikidata-surnames.py: to download surnames from wikidata in a specific country

These wikidata datasets are a subset of datasets retrieved from
statistical institutions due to that in Wikipedia/Wikidata there are
important people for each country, but you can find it useful if you
have not names in a country or if you need a test dataset about names
and gender in a country. But you must not trust in the top,
frequencies, ...  given by these datasets, there are exploratory data,
only.

Datasets:
+ You can access to Russia names in cyrillic alphabet (ru_ru) and
  latin alphabet (ru_en)
 
* v0.4.2
Improvements towards reproducible science:
+ [X] adding download.sh to many names folders
+ [X] updating several datasets from statistical institution websites
+ [X] updating infofeatures to changes in source and new datasets

* v0.4.1

Cleaning code:
+ [X] PEP8 reached using pycodestyle
+ [X] remove unused imports
+ [X] delete buggy rows in datasets derived from comments

New features:
+ percentage2names.py: to create datasets with a specific range of
  percentage of males or females
+ launchpad2gender.py: start script to use the perceval feature about
  launchpad (experimental in Damegender, now)

* v0.4.0
The goal with this release Damegender is a good number of countries,
so a squirrel can go from East to Western in the world with countries
with official statistics released with Open Data :)

The news respect 0.3.8 are:
New countries:
+ Russia (1434 females and 3357 males)

New features:
+ newspaper2gender.py: to guess the author's gender from a newspaper
  article url
+ fixes and improvements related to international dataset

* v0.3.8
New countries:
+ Norway (1015 females 896 males)
* v0.3.7

New countries:
+ Sweden (1079 males and 974 females)

* v0.3.6

New commands:
+ csv2jsonapirest.py: to download names with json api files

New countries:
+ Switzerland (60693 names)

New Preprint: Damegender: Towards an International and Free Dataset
about Name, Gender and Frequency

Updates in commands about datasets.

* v0.3.5

Refactoring and bug fixing: All source is reaching PEP8 coding style
now.

Improvements in commands:
+ api2gender.py: you can scrap the gender from wikipedia with
  --api=wikipedia. Before, you can use --api=wikidata, but this way
  (sparql) is worst in the current state of the development.

* v0.3.4

New names:
+ China (2614 females and 2614 males)
+ Turkey (116114 females and 67309 males)

New commands:
+ mergeinterfiles.py: merge dataset files

* v0.3.3

New names from oficial Open Data statistics:
+ Denmark (62072 males and 79235 females)
+ France (16660 males and 19783 females)

Creating inter names from all countries with Open Data:
+ 259395 males
+ 279863 females

Improvements to csv2gender such as new arguments:
- skip_header
- delete_duplicated
- outimg
- outcsv
- title


* v0.3.2
+ csv2gender.py: add --verbose argument

New names from oficial Open Data statistics:
+ Belgium (14208 names)
+ Slovenia (8788 names)
+ Austria (1899 names)
+ Deutchsland (22368 names)
+ Mexico (16122 names)

* v0.3.1
+ top.py: add --position argument, fix --less
+ mail2gender.py and git2gender.py: it shows males and females
+ app/dame_statistics.py: created due to refactor in app/dame_gender.py
+ csv2gender.py: add --noshow argument
+ jokes.py: created. It's about damegender tips written as jokes.
+ manual: new sections
+ Now we have a dual license and I add scripts to change licenses

* v0.2.11
We are starting to count males and females in Internet Communities:
+ count-debian-gender.py: Debian Project (https://www.debian.org)
+ count-forbes.py: Forbes list about most richest people (https://www.forbes.com/)
+ count-gnu.py: GNU Project (https://www.gnu.org)
+ count-kernel.py: Kernel Project (https://www.kernel.org/)
+ count-scientifics.py: Scientifics in Spain (https://www.webometrics.info/en/GoogleScholar/Spain)
+ csv2gender.py: improved for any dataset, not only the Lucia and Helena dataset.
+ git2gender.py: we have fixed a lot of bugs
+ surname.py: we have added --spanish_provinces using top 50 surnames per province datasets
+ divide testsbycommandsextranet in testsbycommandsperceval and testsbycommandsextraapis
* v0.2.10
+ top.py: print lists about the most used names in different countries
+ count-scientifics.py: counting scientifics in Spain

* v0.2.9
New names from oficial Open Data census:
+ Ireland (382 names)
+ Iceland (326 names)
+ Finland (11449 names)

* v0.2.8
New names from oficial Open Data census:
+ Canada (107339 names)
+ New Zealand (6600 names)
+ Australia (52978 names)
+ Portugal (3999 names)

Create:
+ logs-errors.sh: execute allnoundefined.csv with different ML models of errors.py to generate all logs needed
+ manual/damegender.texi, manual/damegender.pdf: we have grouped some articles and ideas in a book format (not finished)

Refactor:
+ errors.py

Updating (more names, new calculus and results):
+ articles/damegender.pdf
+ files/datamodels/*sav


* v0.2.7
+ count-debian-gender.py: add example to count males and females in debian keyring
+ ethnicity.py: race about a name. Source: USA census
+ surname.py: guess surname Spain and United States of America supported
+ surnameincountries.py: about countries where a surname appears. Source: INE
+ readme.sh: now you can convert the readme from org to markdon with this script
+ add adaboost ml algorithm

* v0.2.6
+ roc.py: to deploy roc curves to measure ML
+ regenerate-ml-json.sh: execute all options of damegender2json.py to generate all json needed
+ logs-accuracies.sh: execute all options of accuracy.py to generate all logs needed
+ logs-confusion.sh: execute all options of confusion.py to generate all logs needed
+ api2gender.py: starting the option to use wikidata
* v0.2.5

+ Recreated all datamodels with new datasets. Augmented the accuracies with this feature!
+ Namsor stuff has been updated to Namsor2
* v0.2.4

Now the next datasets available from main.py in damegender
+ [X] United Kingdom
+ [X] United States of America
+ [X] Uruguay
+ [X] Lucía Santamaría and Helena

* v0.2.3

+ Added damegender2json.py to generate files with ML results.
+ Created ML json files
+ Added new ML algorithms: tree and mlp (neural network)
* v0.2.1

+ Added downloadjson.py to download names from csv to one json file we
  have rewrited accuracy.py, confusion.py and errors.py to make this
  calculus offline
* v0.1.9

+ Improved the test system with testing from python commands with bash.
+ Added nameincountries.py to guess a name in different countries
+ main.py: added bernoulliNB ML algorithm and support to genderguesser
+ confusion.py: adding support to different dimensions
+ accuracy.py: added bernoulliNB ML algorithm
+ errors.py: adding genderapi and namsor support
+ csv2gender.py: Minor chances
+ rewriting damemodels.py to postinstall.py to recreate all files created with scripts from original files (not only ML models)
+ mail2gender.py: small fix, avoid duplicated
+ infofeatures.py: is related to letter_a, last_letter_a, last_letter_o, last_letter_consonant, last_letter_vocal, first_letter, first_letter_consonant, first_letter_vocal
+ pca support with pca-components.py and pca-features.py
* v0.0.36

First version packaged.
+ The application is supporting test with nose
+ main.py is returning names in english and spanish
+ api2gender.py is for return names from main apis
+ confusion.py is giving support for main apis
+ accuracy.py is giving support for main apis
+ errors.py is giving support for genderize, damegender, genderguesser and nameapi
+ apikeyadd.py allows create a password file for apis
+ csv2gender.py is only for partial.csv and all.csv
+ damemodels.py is creating sav files for machine learning algorithms with scikit
+ gendergoogle.py is a prototype to calculate gender from google results with a name
+ git2gender.py is a prototype to return number of males and females in a git repository
+ mail2gender.py is a prototype to return number of males and females in a mailing list
+ infofeatures.py is related to last_letter_a, last_letter_consonant, last_letter_vocal
+ pca support is only a prototype
