#+TITLE: Ciencias Sociales para Damegender
#+h3: David Arroyo Menéndez 
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez 
#+EMAIL: davidam@gnu.org
#+DATE: 18/04/2020
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />


* Resumen
Un estudio sociológico se compone de alguna pregunta de investigación,
un diseño muestral, un trabajo de campo, un análisis y unos resultados
con sus conclusiones. Una de las variables más importantes para casi
cualquier diseño muestral es la variable sexo, esta puede ser
preguntada directamente a la persona, pero no siempre, especialmente en
estudios dónde se recupera la información desde Internet: listas de
correo, grupos de news, redes sociales, blogs, Wikipedia, artículos
científicos, ... Las herramientas de detección de género a partir del
nombre, permiten que dado un nombre y/o apellidos devuelvan el sexo,
junto con una probabilidad asociada. También es posible inferir otros
aspectos como nacionalidad, etnicidad, raza, ... Todas estas variables
tienen gran peso en casi cualquier estudio de sociología. En este
artículo se da un repaso a las diferentes fuentes de datos tanto para
construir este tipo de herramientas como para aplicarlas, así como una
revisión a las aportaciones en las diferentes fases en un trabajo
sociológico.

* Introducción

En este momento las herramientas de detección de género a partir del
nombre son las grandes desconocidas de la sociología, sin embargo, van
a permitir determinar una de las variables más determinantes a la hora
de hacer estudios en ciencias sociales, la variable sexo, en el caso
de tener al menos el nombre y, esto es así, en una gran cantidad de
situaciones en la actual Internet.

Damegender proporciona una solución Python con Bash, aportando en este
momento 8 datasets Open Data aportados por diferentes gobiernos para
tener una completa lista de nombres en al menos inglés, español y
francés, junto con las herramientas matemáticas para evaluar precisión
y determinar errores, así mismo se facilita el acceso a las
herramientas comerciales tanto para hacer comparativas como para
utilizarlas desde Damegender. También aporta una solución de
predicción de nombres basada en algoritmos de Machine Learning de la
librería Python Scikit. 

* Herramientas sobre las que aplicar Herramientas de Detección de Género a partir del Nombre

** Git support

Hay muchas comunidades de compartición de código fuente algunas con
bastantes usuarios son Github, Gitlab, Savannah, ... En un momento en
el que empresas como Google, Microsoft, Amazon, Facebook, ... llegan a
concentrar bastante riqueza crear estudios en repositorios tiene
potencia de indicador económico. Para determinar el género es posible
hacer inferencias desde nombre y apellidos e incluso desde
imágenes. 

** Buscadores

Seguramente los búscadores del futuro detecten la string que
introducimos como un nombre y nos digan el género, tal y como hoy
detecta que es una entrada de Wikipedia y proporcionan cierta
información.

Ahora mismo es posible conteos en buscadores utilizando dos strings el
nombre y el genero y detectar si hay más resultados de búsqueda como
masculino o como femenino (Ej: Andrea + masculino versus Andrea +
femenino).

** Trabajo colaborativo

Hay herramientas de trabajo colaborativo (jenkins, jira, launchpad,
remdmine, bugzilla, bugzillarest, ...) desde la que suele ser posible,
o al menos sencillo de implementar una casilla de género o sexo, una
foto y también nombre y apellidos.

** Software para wikis

La wikipedia es uno de los 10 sitios más utilizados de Internet
teniendo acceso a todo el conocimiento libre del mundo, así recuperar
datos

** Grupos de discusión, correo electrónico, o noticias
En grupos de discusión, correo electrónico, o noticias no es habitual
el declarar el sexo (género) de una persona de manera explícita. De
hecho, en los estándares de correo electrónico, o news esto no es
posible *CITA* rfc2646, rfc5538. La puntuación de personas en lugares
como Stackoverflow tienen alta correlación con la influencia de
desarrolladores en código *CITA Aleksander*. 

https://tools.ietf.org/html/rfc2646

** Mensajería

Cuando una persona participa en grupos de mensajería síncrona slack,
telegram, irc, ... a veces es difícil determinar el género de las
personas que participan en él, por ejemplo, aplicando Damegender en
estos grupos sería posible determinar a partir de los nicks utilizados
las personas que son mujeres y/o hombres.

** Redes Sociales

Hay sendos estudios acerca de cómo determinar hombres y mujeres en
Twitter. Esta herramienta por su amplia difusión hay un número de
personas suficiente para generar población suficiente para muestreos
en Internet, por lo que determinar sexo y acercarse estadísticamente a
la pertenencia a cultura, raza, o nacionalidad.


* Aportaciones de las Herramientas de Detección de Género a partir del nombre a diferentes fases de un estudio sociológico

** TODO Cuali/Cuanti

Tanto los estudios cualitativos (ej: grupos de discusión, entrevistas,
...) como los cuantitativos (ej: encuestas) tienen unas fases que
requieren de un diseño muestral. Las variables sexo y edad son
perennes en los diferentes estudios sociológicos.

(*CITA*: La
encuesta: una perspectiva general metodológica) /Lo usual es utilizar
como variables para establecer las cuotas las siguientes: sexo, edad,
estado civil, nivel de educación alcanzado y/o la actividad laboral u
ocupación, es decir, variables cuya información está disponible para
la población (por tanto, las variables recogidas en los censos de
población o en las estadísticas oficiales); también es habitual
utilizar 2 o 3 variables o como mucho cuatro.

** TODO Preguntas de Investigación y Diseño del Estudio

+ [X] No afecta

** TODO Marco teórico

+ [X] No afecta

** TODO Diseño Muestral

*CITA DE IMPORTANCIA DE LA VARIABLE SEXO EN INVESTIGACIÓN SOCIAL*

** TODO Trabajo de Campo
*** Encuestas on-line

+ [ ] Verificar que la persona presta atención
+ [ ] No está timando una posible encuesta de pago

*** Encuestas normales

+ [ ] Verificar un posible error. En la mayoría de encuestas con
  diseño muestral aleatorio el nombre se anonimiza, no así en las del
  censo, o quizás encuestas corporativas. En encuestas anonimizadas a
  veces se toma el contacto, esto es, un email simple, pero puede
  acompañar un nombre y apellido. En todos los casos en los que el
  nombre y el correo electrónico

*** Grupos de discusión y entrevistas

+ [ ] Facilita un poco reconocer que la persona pone atención,
  interés, capacidad a lo que se pregunta, su orientación sexual y
  cuestiones similares si se verifica el sexo con el nombre en caso de
  que el entrevistador dude, esto puede pasar en lo interno de un país
  con realidades culturales diversas/diferentes 
  
** TODO Preparación/revisión de datos y Análisis

+ [ ] En los casos de no respuesta a la pregunta sexo en caso de que
se realizara facilitaría bastante herramientas integradas en las
aplicaciones web, notas de las personas que realizan el estudio
cualitativo, o de dispositivos que se toman los datos una
recomendación en el caso de que se haya rellenado al menos el nombre y
quizás los apellidos.

+ [ ] Permitiría verificar la congruencia de datos 

** TODO Resultados y conclusiones

+ [ ] No afecta

* Conclusiones

Hay grandes volúmenes de datos en Internet de libre acceso que pueden
ser utilizados en estudios sociológicos, sin embargo, muchas veces la
variable sexo es necesario inferirla que es lo que posibilita las
herramientas de detección de género a partir del nombre. Esta
capacidad de hacer inferencia nos permite revisar los pasos de un
estudio sociológico y pensar cómo hacer mejor cada fase teniendo en
cuenta esta innovación tecnológica.
