#+TITLE: Damegender: Writing and Comparing Gender Detection Tools
#+AUTHOR: David Arroyo Menéndez
#+OPTIONS: H:2 toc:nil num:t
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)


* Summary
** About the thesis
+ Thesis Student: David Arroyo Menéndez
+ Title: Writing and Comparing Gender Detection Tools from a Name
+ Thesis Director: Jesús González Barahona
+ Objectives:

To compare APIs to detect gender from a name

To apply machine learning to classify nicknames, diminutives or new names
as male or female

To understand the impact about open data in census about names and gender
versus datasets created by companies or free software communities.

To apply this tools to the scientific communities or communities based on
Internet.

** Abstract

Diversity in software development teams has been identified as one of
the main ingredients of a more productive and healthy software
community. Thus, the interest of the research community in identifying
who is contributing to a project has increased in the last years. In
the software domain, and although other types of diversity exist, this
is particularly important for the case of gender.  Given the large
amount of publicly available data on the software development process
that can be retrieved and analyzed from the Internet (e.g., GitHub,
StackOverflow), the importance of having methods and tools that help
to identify the participation of women within large amounts of data is
desirable. In this paper we present a free software tool, called
damegender, which we have conceived to infer the gender from the name
of a participant.  damegender is based on open databases from official
census and uses Machine Learning. An experimental branch is currently
under development for those cases where instead of names we have
*diminutives or nicknames*. We have compared damegender with other
name-to-gender inference tools, obtaining good results.  We hope the
damegender tool can become a cornerstone for the scientific
advancement of the study of gender (including the gender gap) and
diversity in Information Technology (IT), and in particular in the
*free software community*.

** Download source and article to a make a good tracing

+ git clone https://github.com/davidam/damegender.git

** Introduction (I): Gender detection tools in the bibliography

+ The most used method to infer the gender of participants
is by looking at their name.
+ To infer the gender from faces in images [RPC17], 
+ To infer gender from hand-written annotations [LSB11], 
+ To infer gender from speeches [KAS02].

** Introduction (II): Research

+ we evaluate the quality (and accessibility, including price) of
  different existing solutions;

+ we discuss their limitations; and
 
+ we investigate what happens with those names not included in
  official statistics, for example, nicknames or diminutives

** Introduction (III): Contributions

+ an evaluation of the quality of different solutions applying
  well-known metrics;

+ a tool, called damegender, guessing gender from a name giving
  support to Spanish and English from the open data census provides by
  the states built to understand current technologies in detail; this
  tool has been compared with APIs using an international dataset with
  good results; and

+ a machine learning solution to strings not found in the census
  dataset to approach the problem with nicknames and diminutives;

** Damegender (I): Technologies

+ Natural Language Toolkit (NLTK) for natural language processing [LB02]
+ Scikit for machine learning [PVG+11],
+ Numpy nor numerical computation [VDWCV11], and
+ Matplotlib to visualize results [Hun07]. 
+ At its current point it is linked to Perceval [DCRGB18]

** Datasets (I): Ways to build a good dataset about names

+ A census published with a free license (open census way), 
+ A dataset released with a free license in a free software package
  (free software way),
+ A dataset retrieved from commercial APIs (commercial API way), and 
+ A dataset which is the result of an investigation and that has been
  released publicly (scientific way).

** Datasets (II): Datasets about names for official statistics in Damegender

+ North America: USA and Canada
+ South America: Uruguay
+ Europe: Ireland, United Kingdom, Spain, Portugal, Iceland, Finland 
+ Oceania: Australia, New Zealand

Note: the results in this paper has been reached with Spain, Uruguay, USA and
United Kingdom official statistics.

** 

** Conclusions

The market of gender detection tools is dominated by companies based
on *payment services through APIs*. This market could be changed thanks
to *free software tools and open data* due to give more explicative
results for the user. Although the *machine learning* techniques is not
new in this field, it's *an incentive for researchers* in computer
science create free software tools.

These advances in computer science could be giving support to study
the gender gap in repositories and mailing lists.
