\input texinfo   @c -*-texinfo-*-
@comment $Id@w{$}
@comment %**start of header
@include version.texi
@settitle Damegender Manual @value{VERSION}
@syncodeindex pg cp
@comment %**end of header
@copying
This manual is for Damegender (version @value{VERSION}, @value{UPDATED}),
which is an example in the Texinfo documentation.

Copyright @copyright{} 2020 David Arroyo Men@'endez

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying

@dircategory Damegender
@direntry
* installation: (installation)Installation.
@end direntry

@titlepage
@title Damegender Manual: Counting Males and Females in Internet Communities
@subtitle for version @value{VERSION}, @value{UPDATED}
@author David Arroyo Men@'endez (@email{davidam@@gnu.org})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Damegender

This manual is for Damegender (version @value{VERSION}, @value{UPDATED}).
@end ifnottex

@menu
* Introduction::
* Installation::
* GNU Free Documentation License::
* Index::
@end menu

@node Introduction
@chapter Introduction

Damegender is a gender detection tool from the name coded by David Arroyo MEnéndez (DAME)

...

@node Installation
@chapter Installation

Possible Debian/Ubuntu dependencies:
@example
$ sudo apt-get install python3-nose-exclude python3-dev dict dict-freedict-eng-spa dict-freedict-spa-eng dictd
@end example

Now, to install damegender from sources:
@example
$ git clone https://github.com/davidam/damegender
$ cd damegender
$ pip3 install -r requirements.txt
@end example

Now, to install damegender with python package:
@example
$ python3 -m venv /tmp/d
$ cd /tmp/d
$ source bin/activate
$ pip install --upgrade pip
$ pip3 install damegender
$ cd lib/python3.5/site-packages/damegender
$ python3 main.py David
@end example

To install apis extra dependencies:
@example
$ pip3 install damegender[apis]
@end example

To install mailing lists and repositories extra dependencies:
@example
$ pip3 install damegender[mails_and_repositories]
@end example

To install all possible dependencies

@example
$ pip3 install damegender[all]
@end example

Currently you can need an api key from:

@itemize @bullet
@item
https://store.genderize.io/documentation 

@item
https://gender-api.com

@item
https://www.nameapi.org/

@item
https://v2.namsor.com/NamSorAPIv2/sign-in.html
@end itemize

To configure your api key you can execute:
@example
$ python3 apikeyadd.py
@end example



@node GNU Free Documentation License
@appendix GNU Free Documentation License

@include fdl.texi


@node Index
@unnumbered Index

@printindex cp

@bye
